[package]
name = "RusDJ"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
ness_stretch = "0.5.1"
serde = "1.0.214"
slint = "1.8.0"
symphonia = "0.5.4"
